---
- name: Check if certificate already exists.
  stat:
    path: '{{ certbot_public_cert }}'
  register: letsencrypt_cert

- name: Stop services to allow certbot to generate a cert.
  service:
    name: nginx
    state: stopped
  when: not letsencrypt_cert.stat.exists

- name: Generate new certificate if one doesn't exist.
  command: '{{ certbot_create_command }}'
  when: not letsencrypt_cert.stat.exists

- name: Start services after cert has been generated.
  service:
    name: nginx
    state: started
  when: not letsencrypt_cert.stat.exists
