---
- name: Enable HTTP & HTTPS ports
  iptables:
    comment: Redirects
    chain: INPUT
    jump: ACCEPT
    source: '0.0.0.0/0'
    protocol: 'tcp'
    destination_port: '{{ item }}'
  with_items:
    - 80
    - 443
  notify:
    - Save iptables rules
